spring:
  application:
    name: convenient-stores-springboot
  datasource:
    url: jdbc:mysql://localhost:3306/convenient_stores
    username: root
    password: '012345'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
    devtools:
      livereload:
        enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
